import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:injectable/injectable.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../domain/entities/check_in.dart';
import '../../domain/repositories/check_in_repository.dart';
import 'check_in_state.dart';

@injectable
class CheckInCubit extends Cubit<CheckInState> {
  final ICheckInRepository _repository;
  final SupabaseClient _client;

  CheckInCubit(this._repository, this._client) : super(CheckInInitial());

  Future<void> submitCheckIn(String circleId) async {
    final userId = _client.auth.currentUser?.id;
    if (userId == null) {
      emit(const CheckInError('User not authenticated'));
      return;
    }

    emit(CheckInLoading());
    
    final checkIn = CheckInEntity(
      id: '', // Generated by DB
      userId: userId,
      circleId: circleId,
      checkedInAt: DateTime.now(),
    );

    final result = await _repository.checkIn(checkIn);
    
    result.fold(
      (failure) => emit(CheckInError(failure.message)),
      (_) => emit(CheckInSuccess()),
    );
  }

  Future<void> loadCheckIns(String circleId) async {
    emit(CheckInLoading());
    final result = await _repository.getCircleCheckIns(circleId);
    
    result.fold(
      (failure) => emit(CheckInError(failure.message)),
      (checkIns) => emit(CheckInLoaded(checkIns)),
    );
  }
}
