import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:injectable/injectable.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../domain/entities/circle_entity.dart';
import '../../domain/repositories/circle_repository.dart';
import 'circle_state.dart';

@injectable
class CircleCubit extends Cubit<CircleState> {
  final ICircleRepository _circleRepository;
  final SupabaseClient _supabaseClient;

  CircleCubit(this._circleRepository, this._supabaseClient) : super(CircleInitial());

  Future<void> loadCircles() async {
    emit(CircleLoading());
    final result = await _circleRepository.getMyCircles();
    result.fold(
      (failure) => emit(CircleError(failure.message)),
      (circles) => emit(CircleLoaded(circles)),
    );
  }

  Future<void> createCircle({
    required String name,
    required String type,
    String? description,
  }) async {
    emit(CircleLoading());
    final userId = _supabaseClient.auth.currentUser?.id;
    if (userId == null) {
      emit(const CircleError('User not authenticated'));
      return;
    }

    final newCircle = CircleEntity(
      id: '', // Will be generated by Supabase
      name: name,
      circleType: type,
      createdBy: userId,
      description: description,
      comfortRadius: 'inner', // Default
      isEncrypted: true,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    final result = await _circleRepository.createCircle(newCircle);
    result.fold(
      (failure) => emit(CircleError(failure.message)),
      (circle) => emit(CircleCreated(circle)),
    );
  }
}
