import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:injectable/injectable.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../../../core/subscription/subscription_service.dart';
import '../../domain/entities/circle_entity.dart';
import '../../domain/repositories/circle_repository.dart';
import 'circle_state.dart';

@injectable
class CircleCubit extends Cubit<CircleState> {
  final ICircleRepository _circleRepository;
  final SupabaseClient _supabaseClient;
  final ISubscriptionService _subscriptionService;

  CircleCubit(
    this._circleRepository,
    this._supabaseClient,
    this._subscriptionService,
  ) : super(CircleInitial());

  Future<void> loadCircles() async {
    emit(CircleLoading());
    final result = await _circleRepository.getMyCircles();
    result.fold(
      (failure) => emit(CircleError(failure.message)),
      (circles) => emit(CircleLoaded(circles)),
    );
  }

  Future<void> createCircle({
    required String name,
    required String type,
    String? description,
    String? avatarUrl,
  }) async {
    emit(CircleLoading());
    final userId = _supabaseClient.auth.currentUser?.id;
    if (userId == null) {
      emit(const CircleError('User not authenticated'));
      return;
    }

    final isEntitled = await _subscriptionService.checkEntitlement('unlimited_circles');
    
    if (!isEntitled) {
      final circlesResponse = await _supabaseClient
          .from('circles')
          .select('id')
          .eq('created_by', userId);
      
      final count = (circlesResponse as List).length;
      if (count >= 1) {
        emit(const CircleError('Free tier is limited to 1 circle. Please upgrade to Tether Plus for unlimited sanctuaries.'));
        return;
      }
    }

    final newCircle = CircleEntity(
      id: '', // Will be generated by Supabase
      name: name,
      circleType: type,
      createdBy: userId,
      description: description,
      avatarUrl: avatarUrl,
      comfortRadius: 'inner', // Default
      isEncrypted: true,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    final result = await _circleRepository.createCircle(newCircle);
    result.fold(
      (failure) => emit(CircleError(failure.message)),
      (circle) => emit(CircleCreated(circle)),
    );
  }
}
